# Generated by Django 3.0.6 on 2020-06-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentive',
            name='tags',
            field=models.ManyToManyField(blank=True, to='incentive.Tag'),
        ),
    ]
