# Generated by Django 3.0.6 on 2020-06-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0002_auto_20200601_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incentive',
            name='tags',
        ),
    ]
