# Generated by Django 3.0.6 on 2020-06-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0003_remove_incentive_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentive',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='incentive.Tag'),
        ),
    ]
