# Generated by Django 3.0.6 on 2020-06-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0004_incentive_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationevent',
            name='intervention_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='socialrelations',
            name='intervention_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='intervention_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='touchevents',
            name='intervention_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='usersactivity',
            name='intervention_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
