# Generated by Django 3.0.6 on 2020-06-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0006_auto_20200607_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='wenetusers',
            name='made_up',
            field=models.IntegerField(default=0),
        ),
    ]
