# Generated by Django 3.0.6 on 2020-06-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0008_auto_20200607_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstatus',
            name='Message_content',
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='Message',
            field=models.TextField(blank=True, default='', max_length=120),
        ),
    ]
