# Generated by Django 3.0.6 on 2020-06-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0009_auto_20200609_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedIncentives',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=120)),
                ('incentive_id', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=120)),
                ('delivered', models.BooleanField(default=False)),
            ],
        ),
    ]
