# Generated by Django 3.0.6 on 2020-06-18 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0010_issuedincentives'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedincentives',
            name='app_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
