# Generated by Django 3.0.6 on 2020-06-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0011_issuedincentives_app_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeDiaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=120)),
                ('incentive_id', models.CharField(max_length=120)),
                ('answer_duration', models.IntegerField()),
                ('notification_timestamp', models.CharField(max_length=255)),
                ('answer_timestamp', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('aid', models.CharField(max_length=255)),
                ('cid', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('question', 'answer', 'answer_timestamp')},
            },
        ),
    ]
