# Generated by Django 3.0.6 on 2020-06-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0012_timediaries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timediaries',
            old_name='incentive_id',
            new_name='intervention_id',
        ),
    ]
