# Generated by Django 3.0.6 on 2020-06-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0013_auto_20200622_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timediaries',
            name='intervention_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
