# Generated by Django 3.0.6 on 2020-12-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0014_auto_20200622_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagesFamily',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('family', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
