# Generated by Django 3.0.6 on 2020-12-24 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0015_messagesfamily'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('groupIncentive', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('condition', models.TextField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incentive.MessagesFamily', to_field='family')),
            ],
        ),
    ]
