# Generated by Django 3.0.6 on 2020-12-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0016_incentivemessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentivemessages',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
