# Generated by Django 3.0.6 on 2021-01-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0017_auto_20201224_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incentivemessages',
            name='condition',
        ),
        migrations.AddField(
            model_name='messagesfamily',
            name='condition_frequency',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='messagesfamily',
            name='condition_inactivity',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='messagesfamily',
            name='condition_repeat',
            field=models.IntegerField(default=2),
        ),
    ]
