# Generated by Django 3.0.6 on 2021-01-26 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0018_auto_20210124_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('incentiveID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incentive.IncentiveMessages')),
            ],
        ),
    ]
