# Generated by Django 3.0.6 on 2021-01-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0019_messagetag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagetag',
            old_name='incentiveID',
            new_name='incentive',
        ),
        migrations.RemoveField(
            model_name='messagetag',
            name='name',
        ),
        migrations.AddField(
            model_name='messagetag',
            name='tag_name',
            field=models.CharField(db_index=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagetag',
            name='tag_value',
            field=models.CharField(db_index=True, default=1, max_length=100),
            preserve_default=False,
        ),
    ]
