# Generated by Django 3.0.6 on 2021-02-01 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0020_auto_20210126_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentivemessages',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incentive.MessagesFamily', to_field='family', verbose_name='family'),
        ),
    ]
