# Generated by Django 3.0.6 on 2021-02-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0021_auto_20210201_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='app_id',
            field=models.CharField(default='I2AFRCOXx3', max_length=120),
            preserve_default=False,
        ),
    ]
