# Generated by Django 3.0.6 on 2021-02-07 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0022_taskstatus_app_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeNetApps',
            fields=[
                ('app_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('app_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IncentiveApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incentive.WeNetApps')),
                ('incentive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incentive.IncentiveMessages')),
            ],
        ),
    ]
