# Generated by Django 3.0.6 on 2021-02-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0023_incentiveapp_wenetapps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersActivity',
        ),
    ]
