# Generated by Django 3.0.6 on 2021-02-23 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0024_delete_usersactivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wenetusers',
            old_name='made_up',
            new_name='cohort',
        ),
    ]
