# Generated by Django 3.0.6 on 2021-02-23 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0025_auto_20210223_0928'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wenetusers',
            unique_together={('user_id', 'app_id')},
        ),
    ]
