# Generated by Django 3.0.6 on 2021-02-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0026_auto_20210223_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersCohorts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=120)),
                ('app_id', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=120)),
                ('cohort', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('user_id', 'app_id')},
            },
        ),
    ]
