# Generated by Django 3.0.6 on 2021-02-23 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0027_userscohorts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wenetusers',
            old_name='cohort',
            new_name='made_up',
        ),
    ]
