# Generated by Django 3.0.6 on 2021-07-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0028_auto_20210223_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskstatus',
            old_name='Action',
            new_name='action',
        ),
        migrations.RemoveField(
            model_name='taskstatus',
            name='Message',
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
