# Generated by Django 3.0.6 on 2021-07-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0029_auto_20210713_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskstatus',
            old_name='action',
            new_name='taskTypeId',
        ),
        migrations.RemoveField(
            model_name='taskstatus',
            name='task_id',
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='label',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
