# Generated by Django 3.0.6 on 2021-07-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0031_auto_20210720_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='label',
            field=models.CharField(blank=True, default='nolabel!', max_length=120),
        ),
    ]
