# Generated by Django 3.0.6 on 2021-08-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0032_auto_20210720_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeSteeringIncentiveMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entityId', models.CharField(max_length=22)),
                ('taskTypeId', models.CharField(max_length=120)),
                ('label', models.CharField(blank=True, default='nolabel!', max_length=120)),
                ('max_repeat', models.PositiveIntegerField()),
                ('frequency', models.PositiveIntegerField()),
                ('inactivity_period', models.PositiveIntegerField()),
                ('app', models.CharField(max_length=120)),
            ],
        ),
    ]
