# Generated by Django 3.0.6 on 2021-08-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0033_badgesteeringincentivemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgesteeringincentivemessage',
            name='message',
            field=models.CharField(default='test', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='badgesteeringincentivemessage',
            name='label',
            field=models.CharField(max_length=120),
        ),
    ]
