# Generated by Django 3.0.6 on 2021-10-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0036_auto_20211013_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgesteeringincentivemessage',
            name='inactivity_period',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='taskId',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
