# Generated by Django 3.0.6 on 2021-11-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentive', '0037_auto_20211019_1714'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BadgeSteeringIncentiveMessage',
        ),
        migrations.RemoveField(
            model_name='messagetag',
            name='incentive',
        ),
        migrations.RenameField(
            model_name='incentivemessages',
            old_name='created',
            new_name='createdAt',
        ),
        migrations.RemoveField(
            model_name='incentivemessages',
            name='family',
        ),
        migrations.RemoveField(
            model_name='incentivemessages',
            name='groupIncentive',
        ),
        migrations.RemoveField(
            model_name='incentivemessages',
            name='status',
        ),
        migrations.AddField(
            model_name='incentivemessages',
            name='app',
            field=models.CharField(default='test', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incentivemessages',
            name='entityId',
            field=models.CharField(default='test', max_length=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incentivemessages',
            name='frequency',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incentivemessages',
            name='inactivity_period',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incentivemessages',
            name='inactivity_range_bottom',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incentivemessages',
            name='inactivity_range_top',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incentivemessages',
            name='label',
            field=models.CharField(default='test', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incentivemessages',
            name='max_repeat',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incentivemessages',
            name='taskTypeId',
            field=models.CharField(default='test', max_length=120),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='IncentiveApp',
        ),
        migrations.DeleteModel(
            name='MessagesFamily',
        ),
        migrations.DeleteModel(
            name='MessageTag',
        ),
    ]
