FROM python:3.6
ENV PYTHONUNBUFFERED 1
RUN apt-get -y update && apt-get -y upgrade


RUN apt-get install -y cron nano
RUN mkdir /code
WORKDIR /code
ADD test_cron.py requirements.txt /code/
RUN touch /code/incentive_cron.log

RUN pip3 install -r requirements.txt
COPY crontab /etc/cron.d/cjob
RUN chmod 0644 /etc/cron.d/cjob
CMD cron -f